[project]
name = "comfyui-switchboard"
description = "ComfyUI Switchboard - toggle ComfyUI groups or individual nodes on/off (bypass or mute), manually or from a wired boolean. A more flexible take on rgthree's Fast Group Bypasser."
version = "1.0.3"
license = { file = "LICENSE" }
readme = "README.md"

[project.urls]
Repository = "https://github.com/Oratorian/ComfyUI-Switchboard"
#  Used by Comfy Registry https://registry.comfy.org
"Bug Tracker" = "https://github.com/Oratorian/ComfyUI-Switchboard/issues"

[tool.comfy]
PublisherId = "oratorian"
DisplayName = "ComfyUI Switchboard"
Icon = ""
includes = []